"""
StarGuard AI - Shared UI Components
Reusable UI components for the Shiny application
"""

from htmltools import Tag, tags
from shiny import ui


def create_header() -> Tag:
    """
    Reusable header component with consistent branding.
    Used across all pages for uniform look and feel.
    """
    return tags.div(
        tags.style("""
            .app-header {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                padding: 25px 35px;
                margin-bottom: 25px;
                border-radius: 10px;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            }
            .app-header h2 {
                color: white;
                margin: 0;
                font-size: 2.2em;
                font-weight: 600;
                text-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
            }
            .app-header .subtitle {
                color: rgba(255, 255, 255, 0.95);
                margin: 8px 0 0 0;
                font-size: 1.15em;
                font-weight: 400;
                font-style: italic;
            }
            .app-header .star-icon {
                display: inline-block;
                font-size: 1.3em;
                vertical-align: middle;
                margin-right: 5px;
                animation: pulse 2s infinite;
            }
            @keyframes pulse {
                0%, 100% { opacity: 1; }
                50% { opacity: 0.7; }
            }
        """),
        tags.div(
            tags.h2(
                tags.span("⭐", class_="star-icon"),
                "StarGuard AI | Medicare Advantage Intelligence Platform",
            ),
            tags.p(
                "Compound AI for Star Ratings, Risk Adjustment & Member Retention",
                class_="subtitle",
            ),
            class_="app-header",
        ),
    )


# Embedded base64 QR code for demo URL (generated by generate_qr_base64.py)
_QR_BASE64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUoAAAFKAQAAAABTUiuoAAACTUlEQVR4nO2bQW7jMAxFH2sBXco36FHkq/VmzlFyA3sZQMafhaTYbdFBMoAnWpALI7LfggBB8ktiTDxol7dHSXDUUUffYLVq02pmNm5mNoKZBdqn0ImvjjJIkg4lUbqakRYgSZKWcx1w9Cm0Zk/MaF7fBQziMkLJvOl0Bxx9yMJxsY4YgBFv9kN+vNxXR7+gMVOqXroGzMb/7oCjf7eSWy2PBgGbqRRBAKKA9TwHHH0CrckEQFoGfX9UG6T55b46Gmr2ALCCWEGXEdNlHDg2r5f76ugbrIG6y/rI5RfEjE0xYxObcfH9Vh8okjKao6R5f1uWQ9Hy0uKVsAuUEgote2RqLythLNvmKI9WL+hmZh83k5bNIKrujlkDNq0B6eqVsAu05tYc1URglOqpRpQ0x1yPnzy3Xo+WaJFa1avLBUobS6qp5tHqAC3tqVhSLjHaBUbbdHm0ukCbotilxr0mpgWqwHCV0QdaozXT6t9dHZavM+DR6gU9dKtWE1tapSI/Mq7ge0FbMsVMu368t7F7lrkm7AeNNaP0Oba3SRl9flTRcbYDjj5qAdjqI2kLsI6UR7oawGanOuDoP/StNn6hmaEcETadCLiC7wT9er/1pY3d9YZrwp7QfeZpkE3xZhwCBeXivxNfHd1nnm7Gxd5Vj3HZzGwcZNPpDjj6mB22wzWZaqrtd15eCXtBw7e1wWakeQsQAeKCpWvIHfjqaDsilLSft7fNsquMDtGtzLrDaqY53upQdRlTi/mInuOAow/az5Hc38z/EeSoo8+gfwBmj7Ytr/h7sQAAAABJRU5ErkJggg=="


def create_footer() -> Tag:
    """Complete footer with all contact info, QR code, and Mobile Ready badge"""
    return ui.div(
        ui.tags.style("""
            /* Footer styling */
            .app-footer {
                margin-top: 40px;
                padding-top: 20px;
                border-top: 2px solid #e0e0e0;
            }

            .footer-contact-info {
                padding: 10px 0;
            }

            .footer-contact-info p {
                margin: 5px 0;
                font-size: 0.9em;
                color: #555;
            }

            .footer-contact-info strong {
                color: #2c3e50;
            }

            .footer-contact-info a {
                color: #667eea;
                text-decoration: none;
                font-weight: 500;
            }

            .footer-contact-info a:hover {
                text-decoration: underline;
            }

            .footer-qr-section {
                text-align: center;
                padding: 10px;
            }

            .footer-qr-section p {
                font-size: 0.85em;
                color: #555;
                font-weight: 600;
                margin-bottom: 8px;
            }

            .footer-qr-section img {
                max-width: 120px;
                height: auto;
                display: block;
                margin: 0 auto 10px auto;
                border: 3px solid #667eea;
                border-radius: 8px;
                padding: 8px;
                background: white;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            }

            .footer-mobile-badge {
                text-align: center;
                margin-top: 10px;
            }

            .footer-mobile-badge span {
                display: inline-block;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                padding: 6px 14px;
                border-radius: 20px;
                font-size: 0.8em;
                font-weight: 600;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);
            }

            .footer-demo-info {
                background: #f8f9fa;
                padding: 20px;
                border-radius: 8px;
                margin-top: 20px;
            }

            .footer-demo-info h6 {
                color: #2c3e50;
                margin-top: 0;
                margin-bottom: 10px;
                font-weight: 600;
            }

            .footer-demo-info ul {
                color: #7f8c8d;
                font-size: 0.85em;
                line-height: 1.6;
                margin-bottom: 10px;
            }

            .footer-copyright {
                text-align: center;
                color: #95a5a6;
                font-size: 0.8em;
                margin-top: 15px;
                padding-top: 15px;
                border-top: 1px solid #e0e0e0;
                font-style: italic;
            }

            @media print {
                .footer-mobile-badge {
                    display: none;
                }

                .footer-demo-info {
                    display: none;
                }

                .footer-qr-section img {
                    max-width: 1.5in !important;
                    border: 2px solid #000 !important;
                }
            }
        """),
        ui.div(
            ui.row(
                ui.column(
                    6,
                    ui.div(
                        ui.tags.p(
                            ui.tags.strong(
                                "Medicare Advantage Intelligence Platform | StarGuard AI"
                            )
                        ),
                        ui.tags.p(
                            "📧 ",
                            ui.tags.a(
                                "reichert.starguardai@gmail.com",
                                href="mailto:reichert.starguardai@gmail.com",
                                target="_blank",
                            ),
                        ),
                        ui.tags.p(
                            "💼 ",
                            ui.tags.a(
                                "linkedin.com/in/robertreichert-healthcareai",
                                href="https://linkedin.com/in/robertreichert-healthcareai",
                                target="_blank",
                            ),
                        ),
                        ui.tags.p(
                            "🔗 ",
                            ui.tags.a(
                                "Live Demo: tinyurl.com/bdevpdz5",
                                href="https://tinyurl.com/bdevpdz5",
                                target="_blank",
                            ),
                        ),
                        class_="footer-contact-info",
                    ),
                ),
                ui.column(
                    6,
                    ui.div(
                        ui.tags.p("Scan to Try Demo:"),
                        ui.tags.img(src=_QR_BASE64, alt="StarGuard AI Demo QR Code"),
                        ui.div(ui.tags.span("📱 Mobile Ready"), class_="footer-mobile-badge"),
                        class_="footer-qr-section",
                    ),
                ),
            ),
            ui.tags.hr(style="margin-top: 25px; border-color: #e0e0e0;"),
            ui.div(
                ui.tags.h6(
                    "About This Demonstration",
                    style="color: #2c3e50; margin-top: 20px; margin-bottom: 10px; font-weight: 600;",
                ),
                ui.tags.p(
                    ui.tags.strong("Demonstration Data Sources:"),
                    style="margin: 10px 0 5px 0; color: #555; font-size: 0.9em;",
                ),
                tags.ul(
                    tags.li("CMS Synthetic Public Use Files (Medicare claims data)"),
                    tags.li("MIMIC-IV Clinical Database (de-identified clinical notes)"),
                    tags.li("AHRQ Social Determinants of Health Database"),
                    tags.li("Synthetic sentiment data (call transcripts)"),
                    style="color: #7f8c8d; font-size: 0.85em; line-height: 1.6; margin-bottom: 10px;",
                ),
                ui.tags.p(
                    ui.tags.strong("Key Features Demonstrated:"),
                    style="margin: 10px 0 5px 0; color: #555; font-size: 0.9em;",
                ),
                tags.ul(
                    tags.li(
                        "Compound AI architecture with specialized agents (Sentiment, SDoH, Channel, Strategy)"
                    ),
                    tags.li(
                        "Multi-modal data integration (claims + EHR + sentiment + social determinants)"
                    ),
                    tags.li("Agentic RAG for personalized member outreach via Anthropic Claude"),
                    tags.li("Real-time portfolio optimization with ROI modeling"),
                    tags.li("HIPAA-compliant architecture design patterns"),
                    style="color: #7f8c8d; font-size: 0.85em; line-height: 1.6; margin-bottom: 15px;",
                ),
                ui.tags.p(
                    "💡 ",
                    ui.tags.em(
                        "This platform demonstrates production-grade AI capabilities using realistic healthcare data. All member data is synthetic or de-identified."
                    ),
                    style="color: #667eea; font-size: 0.85em; margin-top: 10px; font-style: italic;",
                ),
                class_="footer-demo-info",
            ),
            ui.tags.p(
                "© 2026 StarGuard AI | Healthcare AI that delivers ROI, not just insights.",
                class_="footer-copyright",
            ),
            class_="app-footer",
        ),
    )


def sidebar_brand() -> Tag:
    """Sidebar brand section with logo and tagline"""
    return tags.div(
        tags.span("⭐", class_="sg-star"),
        tags.h2("StarGuard AI"),
        tags.p("Medicare Advantage Intelligence Platform", class_="sg-tagline"),
        class_="sg-sidebar-brand",
    )


def nav_group_title(title: str) -> Tag:
    """Navigation group section header"""
    return tags.div(title, class_="sg-nav-group-title")


def page_header(title: str, tagline: str = "", subtitle: str = "") -> Tag:
    """Page header with purple gradient"""
    children = [tags.span("⭐", class_="sg-star"), tags.h1(title)]

    if tagline:
        children.append(tags.p(tagline, class_="sg-header-tagline"))

    if subtitle:
        children.append(tags.p(subtitle, class_="sg-header-subtitle"))

    return tags.div(*children, class_="sg-header")


def metric_card(label: str, value: str, delta: str = "", delta_type: str = "positive") -> Tag:
    """Metric card component"""
    children = [
        tags.div(label, class_="sg-metric-label"),
        tags.div(value, class_="sg-metric-value"),
    ]

    if delta:
        delta_class = f"sg-metric-delta {delta_type}"
        delta_symbol = "↑" if delta_type == "positive" else "↓" if delta_type == "negative" else ""
        children.append(tags.div(f"{delta_symbol} {delta}", class_=delta_class))

    return tags.div(*children, class_="sg-metric-card")


def metrics_row(*cards: Tag) -> Tag:
    """Row container for multiple metric cards"""
    return tags.div(*cards, class_="sg-metrics-row")


def card(title: str = None, *children) -> Tag:
    """Generic content card"""
    card_children = []

    if title:
        card_children.append(tags.h3(title, class_="sg-card-title"))

    card_children.extend(children)

    return tags.div(*card_children, class_="sg-card")


def chart_container(*children) -> Tag:
    """Container for Plotly charts"""
    return tags.div(*children, class_="sg-chart-container")


def controls(*children) -> Tag:
    """Filter panel container"""
    return tags.div(*children, class_="sg-controls")


def security_badge() -> Tag:
    """Security badge with HIPAA information"""
    return tags.div(
        tags.h4("🔒 Secure AI Architecture"),
        tags.p("Healthcare AI that sees everything, exposes nothing."),
        tags.div(
            tags.span("On-Premises", class_="sg-security-tag"),
            tags.span("Zero API Exposure", class_="sg-security-tag"),
            tags.span("HIPAA-First", class_="sg-security-tag"),
        ),
        class_="sg-security-badge",
    )


def tech_badges() -> Tag:
    """Technology stack badges"""
    return tags.div(
        tags.span("🐍 Python"),
        tags.span("📊 Shiny"),
        tags.span("📈 Plotly"),
        tags.span("🐘 PostgreSQL"),
        tags.span("🤖 ML/AI"),
        class_="sg-tech-badges",
    )


def qr_landing_card() -> Tag:
    """QR code landing card"""
    return tags.div(
        tags.a(
            tags.img(src="qr-landing.png", alt="QR Code", class_="sg-qr-code"),
            href="https://tinyurl.com/bdevpdz5",
            target="_blank",
        ),
        tags.p(
            "Scan for portfolio, resume & contact info",
            style="text-align: center; margin-top: 0.5rem; font-size: 0.85rem; color: #6b7280;",
        ),
        class_="sg-card",
        style="max-width: 320px; margin: 0 auto; text-align: center;",
    )


def footer() -> Tag:
    """Footer with brand metrics (legacy; prefer create_footer for consistency)"""
    return tags.div(
        tags.h2("⭐ Medicare Advantage Intelligence Platform | StarGuard AI"),
        tags.p("Turning Data Into Stars"),
        tags.div(
            tags.div(tags.p("2.8–4.1×"), tags.p("ROI")),
            tags.div(tags.p("$148M+"), tags.p("Savings")),
            tags.div(tags.p("Zero"), tags.p("PHI Exposure")),
            class_="sg-footer-metrics",
        ),
        tags.p(
            "⚠️ Portfolio Demonstration: Using synthetic data to showcase real methodology and production-grade analytics.",
            style="font-size: 0.85rem; margin-top: 1rem; color: rgba(255,255,255,0.9);",
        ),
        tags.p(
            "© 2024–2026 Robert Reichert | StarGuard AI™",
            style="font-size: 0.85rem; margin-top: 1rem; color: rgba(255,255,255,0.8);",
        ),
        class_="sg-footer",
    )


def alert_info(text: str) -> Tag:
    """Info alert box"""
    return tags.div(text, class_="sg-alert-info")


def alert_warning(text: str) -> Tag:
    """Warning alert box"""
    return tags.div(text, class_="sg-alert-warning")


def alert_success(text: str) -> Tag:
    """Success alert box"""
    return tags.div(text, class_="sg-alert-success")
